### ISSUE TITLE
fix: gpu 의존성 제거

### ISSUE THREAD

**Issue by e7217** [FinAgent-Lab/market-analysis-team#80]
**수정 항목**
```
...
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
...
```
